export interface DemoCompany {
  id: string;
  name: string;
  website: string;
  industry: string;
  logo_url: string;
  description: string;
  is_verified: boolean;
  verification_status: "verified";
  status: "active";
  official_email: string;
  contact_email: string;
  company_size: string;
  headquarters: string;
  city: string;
  state: string;
  country: string;
  trust_score: number;
}

export interface DemoInternship {
  id: string;
  company_id: string;
  title: string;
  department: string;
  description: string;
  location: string;
  type: "remote" | "hybrid" | "on-site";
  internship_type: string;
  duration: string;
  stipend: string;
  salary_range: string;
  openings_count: number;
  deadline: string;
  start_date: string;
  end_date: string;
  employment_type: string;
  required_experience: string;
  minimum_cgpa: string;
  requirements: string[];
  skills_needed: string[];
  preferred_skills: string[];
  responsibilities: string[];
  eligibility: string;
  perks: string[];
  selection_process: string[];
  status: "approved";
  created_at: string;
  tags: string[];
  company: DemoCompany;
}

export const DEMO_COMPANIES: DemoCompany[] = [
  {
    id: "c0000000-0000-0000-0000-000000000001",
    name: "TechNova Solutions",
    website: "https://technovasolutions.io",
    industry: "Enterprise Software",
    logo_url: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=120&auto=format&fit=crop&q=80",
    description: "Leading enterprise cloud transformation and IoT solutions provider powering Fortune 500 digital systems.",
    is_verified: true,
    verification_status: "verified",
    status: "active",
    official_email: "careers@technovasolutions.io",
    contact_email: "contact@technovasolutions.io",
    company_size: "250-500 employees",
    headquarters: "Bengaluru, Karnataka",
    city: "Bengaluru",
    state: "Karnataka",
    country: "India",
    trust_score: 95,
  },
  {
    id: "c0000000-0000-0000-0000-000000000002",
    name: "ByteForge Technologies",
    website: "https://byteforge.dev",
    industry: "Software Development",
    logo_url: "https://images.unsplash.com/photo-1551434678-e076c223a692?w=120&auto=format&fit=crop&q=80",
    description: "High-growth full-stack software development studio building modern web and mobile applications.",
    is_verified: true,
    verification_status: "verified",
    status: "active",
    official_email: "hr@byteforge.dev",
    contact_email: "contact@byteforge.dev",
    company_size: "50-100 employees",
    headquarters: "Hyderabad, Telangana",
    city: "Hyderabad",
    state: "Telangana",
    country: "India",
    trust_score: 92,
  },
  {
    id: "c0000000-0000-0000-0000-000000000003",
    name: "CloudNest Labs",
    website: "https://cloudnestlabs.com",
    industry: "Cloud & DevOps",
    logo_url: "https://images.unsplash.com/photo-1542744094-3a3172720180?w=120&auto=format&fit=crop&q=80",
    description: "Specialized cloud infrastructure, Kubernetes orchestration, and continuous integration architecture consultancy.",
    is_verified: true,
    verification_status: "verified",
    status: "active",
    official_email: "recruitment@cloudnestlabs.com",
    contact_email: "hello@cloudnestlabs.com",
    company_size: "100-250 employees",
    headquarters: "Pune, Maharashtra",
    city: "Pune",
    state: "Maharashtra",
    country: "India",
    trust_score: 94,
  },
  {
    id: "c0000000-0000-0000-0000-000000000004",
    name: "PixelStack Software",
    website: "https://pixelstack.tech",
    industry: "Web Engineering",
    logo_url: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=120&auto=format&fit=crop&q=80",
    description: "Modern web engineering agency pioneering high-performance React and Next.js applications.",
    is_verified: true,
    verification_status: "verified",
    status: "active",
    official_email: "jobs@pixelstack.tech",
    contact_email: "contact@pixelstack.tech",
    company_size: "20-50 employees",
    headquarters: "Bengaluru, Karnataka",
    city: "Bengaluru",
    state: "Karnataka",
    country: "India",
    trust_score: 91,
  },
  {
    id: "c0000000-0000-0000-0000-000000000005",
    name: "CodeSprint Technologies",
    website: "https://codesprint.in",
    industry: "FinTech & Banking",
    logo_url: "https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=120&auto=format&fit=crop&q=80",
    description: "Enterprise Java microservices and scalable high-frequency financial platform developers.",
    is_verified: true,
    verification_status: "verified",
    status: "active",
    official_email: "talent@codesprint.in",
    contact_email: "info@codesprint.in",
    company_size: "500+ employees",
    headquarters: "Chennai, Tamil Nadu",
    city: "Chennai",
    state: "Tamil Nadu",
    country: "India",
    trust_score: 96,
  },
  {
    id: "c0000000-0000-0000-0000-000000000006",
    name: "VisionAI Labs",
    website: "https://visionailabs.ai",
    industry: "Artificial Intelligence",
    logo_url: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=120&auto=format&fit=crop&q=80",
    description: "Deep tech AI research studio focused on computer vision, autonomous perception, and robotics.",
    is_verified: true,
    verification_status: "verified",
    status: "active",
    official_email: "careers@visionailabs.ai",
    contact_email: "contact@visionailabs.ai",
    company_size: "50-100 employees",
    headquarters: "Bengaluru, Karnataka",
    city: "Bengaluru",
    state: "Karnataka",
    country: "India",
    trust_score: 98,
  },
  {
    id: "c0000000-0000-0000-0000-000000000007",
    name: "QuantumSoft Solutions",
    website: "https://quantumsoft.io",
    industry: "Data Analytics",
    logo_url: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=120&auto=format&fit=crop&q=80",
    description: "Big data analytics, business intelligence dashboards, and predictive decision intelligence frameworks.",
    is_verified: true,
    verification_status: "verified",
    status: "active",
    official_email: "hr@quantumsoft.io",
    contact_email: "contact@quantumsoft.io",
    company_size: "100-250 employees",
    headquarters: "Gurugram, Haryana",
    city: "Gurugram",
    state: "Haryana",
    country: "India",
    trust_score: 90,
  },
  {
    id: "c0000000-0000-0000-0000-000000000008",
    name: "SkyNet Digital",
    website: "https://skynetdigital.net",
    industry: "Mobile Engineering",
    logo_url: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=120&auto=format&fit=crop&q=80",
    description: "Mobile-first product lab engineering native Android and cross-platform Flutter applications.",
    is_verified: true,
    verification_status: "verified",
    status: "active",
    official_email: "hiring@skynetdigital.net",
    contact_email: "contact@skynetdigital.net",
    company_size: "50-100 employees",
    headquarters: "Noida, Uttar Pradesh",
    city: "Noida",
    state: "Uttar Pradesh",
    country: "India",
    trust_score: 89,
  },
  {
    id: "c0000000-0000-0000-0000-000000000009",
    name: "NextWave Technologies",
    website: "https://nextwavetech.com",
    industry: "Frontend Architecture",
    logo_url: "https://images.unsplash.com/photo-1531482615713-2afd69097998?w=120&auto=format&fit=crop&q=80",
    description: "Next-generation web UI studio specializing in micro-frontends and modern design systems.",
    is_verified: true,
    verification_status: "verified",
    status: "active",
    official_email: "careers@nextwavetech.com",
    contact_email: "contact@nextwavetech.com",
    company_size: "100-250 employees",
    headquarters: "Hyderabad, Telangana",
    city: "Hyderabad",
    state: "Telangana",
    country: "India",
    trust_score: 93,
  },
  {
    id: "c0000000-0000-0000-0000-000000000010",
    name: "BluePeak Systems",
    website: "https://bluepeaksystems.com",
    industry: "Cybersecurity",
    logo_url: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=120&auto=format&fit=crop&q=80",
    description: "Cyber defense, ethical penetration testing, and Zero Trust security management firm.",
    is_verified: true,
    verification_status: "verified",
    status: "active",
    official_email: "secops@bluepeaksystems.com",
    contact_email: "contact@bluepeaksystems.com",
    company_size: "250-500 employees",
    headquarters: "Mumbai, Maharashtra",
    city: "Mumbai",
    state: "Maharashtra",
    country: "India",
    trust_score: 97,
  },
  {
    id: "c0000000-0000-0000-0000-000000000011",
    name: "Innovexa Solutions",
    website: "https://innovexasolutions.com",
    industry: "Full Stack Development",
    logo_url: "https://images.unsplash.com/photo-1557804506-669a67965ba0?w=120&auto=format&fit=crop&q=80",
    description: "End-to-end MERN stack product incubator powering SaaS startups across Asia and Europe.",
    is_verified: true,
    verification_status: "verified",
    status: "active",
    official_email: "talent@innovexasolutions.com",
    contact_email: "contact@innovexasolutions.com",
    company_size: "50-100 employees",
    headquarters: "Bengaluru, Karnataka",
    city: "Bengaluru",
    state: "Karnataka",
    country: "India",
    trust_score: 92,
  },
  {
    id: "c0000000-0000-0000-0000-000000000012",
    name: "CoreMatrix Labs",
    website: "https://corematrixlabs.com",
    industry: "Backend Engineering",
    logo_url: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=120&auto=format&fit=crop&q=80",
    description: "High-throughput enterprise backend engineering firm built on Java Spring and distributed databases.",
    is_verified: true,
    verification_status: "verified",
    status: "active",
    official_email: "careers@corematrixlabs.com",
    contact_email: "contact@corematrixlabs.com",
    company_size: "100-250 employees",
    headquarters: "Pune, Maharashtra",
    city: "Pune",
    state: "Maharashtra",
    country: "India",
    trust_score: 94,
  },
  {
    id: "c0000000-0000-0000-0000-000000000013",
    name: "LogicLoop Software",
    website: "https://logicloopsoftware.io",
    industry: "Python & Microservices",
    logo_url: "https://images.unsplash.com/photo-1531973576160-7125cd663d86?w=120&auto=format&fit=crop&q=80",
    description: "Python microservices and FastAPI architecture specialists for API-driven SaaS platforms.",
    is_verified: true,
    verification_status: "verified",
    status: "active",
    official_email: "hr@logicloopsoftware.io",
    contact_email: "contact@logicloopsoftware.io",
    company_size: "20-50 employees",
    headquarters: "Hyderabad, Telangana",
    city: "Hyderabad",
    state: "Telangana",
    country: "India",
    trust_score: 91,
  },
  {
    id: "c0000000-0000-0000-0000-000000000014",
    name: "InnoSpark Technologies",
    website: "https://innosparktech.com",
    industry: "UI/UX & Frontend",
    logo_url: "https://images.unsplash.com/photo-1541746972996-4e0b0f43e02a?w=120&auto=format&fit=crop&q=80",
    description: "Product design agency creating intuitive UI/UX experiences and responsive React frontends.",
    is_verified: true,
    verification_status: "verified",
    status: "active",
    official_email: "design@innosparktech.com",
    contact_email: "contact@innosparktech.com",
    company_size: "50-100 employees",
    headquarters: "Chennai, Tamil Nadu",
    city: "Chennai",
    state: "Tamil Nadu",
    country: "India",
    trust_score: 90,
  },
  {
    id: "c0000000-0000-0000-0000-000000000015",
    name: "FusionStack Pvt Ltd",
    website: "https://fusionstack.in",
    industry: "Data & Distributed Systems",
    logo_url: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=120&auto=format&fit=crop&q=80",
    description: "Distributed data pipeline and blockchain protocol engineering firm for fintech enterprises.",
    is_verified: true,
    verification_status: "verified",
    status: "active",
    official_email: "hiring@fusionstack.in",
    contact_email: "contact@fusionstack.in",
    company_size: "100-250 employees",
    headquarters: "Bengaluru, Karnataka",
    city: "Bengaluru",
    state: "Karnataka",
    country: "India",
    trust_score: 93,
  },
  {
    id: "c0000000-0000-0000-0000-000000000016",
    name: "AlphaCode Systems",
    website: "https://alphacodesystems.com",
    industry: "Software Testing & QA",
    logo_url: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=120&auto=format&fit=crop&q=80",
    description: "Automated QA testing frameworks, Selenium pipelines, and API load testing specialists.",
    is_verified: true,
    verification_status: "verified",
    status: "active",
    official_email: "qa@alphacodesystems.com",
    contact_email: "contact@alphacodesystems.com",
    company_size: "50-100 employees",
    headquarters: "Gurugram, Haryana",
    city: "Gurugram",
    state: "Haryana",
    country: "India",
    trust_score: 88,
  },
  {
    id: "c0000000-0000-0000-0000-000000000017",
    name: "CyberShield Security",
    website: "https://cybershield.sec",
    industry: "Information Security",
    logo_url: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=120&auto=format&fit=crop&q=80",
    description: "Application security audit, penetration testing, and OWASP compliance auditing firm.",
    is_verified: true,
    verification_status: "verified",
    status: "active",
    official_email: "careers@cybershield.sec",
    contact_email: "contact@cybershield.sec",
    company_size: "100-250 employees",
    headquarters: "Mumbai, Maharashtra",
    city: "Mumbai",
    state: "Maharashtra",
    country: "India",
    trust_score: 96,
  },
  {
    id: "c0000000-0000-0000-0000-000000000018",
    name: "DataVerse Analytics",
    website: "https://dataverseanalytics.ai",
    industry: "AI & Machine Learning",
    logo_url: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=120&auto=format&fit=crop&q=80",
    description: "Predictive modeling, Pandas/NumPy analytics, and Machine Learning engineering lab.",
    is_verified: true,
    verification_status: "verified",
    status: "active",
    official_email: "jobs@dataverseanalytics.ai",
    contact_email: "contact@dataverseanalytics.ai",
    company_size: "50-100 employees",
    headquarters: "Hyderabad, Telangana",
    city: "Hyderabad",
    state: "Telangana",
    country: "India",
    trust_score: 95,
  },
  {
    id: "c0000000-0000-0000-0000-000000000019",
    name: "CloudFusion Technologies",
    website: "https://cloudfusiontech.com",
    industry: "DevOps & SRE",
    logo_url: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=120&auto=format&fit=crop&q=80",
    description: "Site reliability engineering, AWS Terraform deployment, and Docker container automation.",
    is_verified: true,
    verification_status: "verified",
    status: "active",
    official_email: "sre@cloudfusiontech.com",
    contact_email: "contact@cloudfusiontech.com",
    company_size: "100-250 employees",
    headquarters: "Noida, Uttar Pradesh",
    city: "Noida",
    state: "Uttar Pradesh",
    country: "India",
    trust_score: 93,
  },
  {
    id: "c0000000-0000-0000-0000-000000000020",
    name: "BrightMind AI",
    website: "https://brightmindai.io",
    industry: "Generative AI & LLMs",
    logo_url: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=120&auto=format&fit=crop&q=80",
    description: "Next-gen Generative AI research lab building custom LLM agents and RAG vector applications.",
    is_verified: true,
    verification_status: "verified",
    status: "active",
    official_email: "ai@brightmindai.io",
    contact_email: "contact@brightmindai.io",
    company_size: "20-50 employees",
    headquarters: "Bengaluru, Karnataka",
    city: "Bengaluru",
    state: "Karnataka",
    country: "India",
    trust_score: 99,
  },
];

export const DEMO_INTERNSHIPS: DemoInternship[] = [
  {
    id: "i0000000-0000-0000-0000-000000000001",
    company_id: "c0000000-0000-0000-0000-000000000009",
    title: "Frontend Developer Intern (React)",
    department: "Engineering",
    description: "Join NextWave Technologies to build responsive, component-driven web interfaces using React.js, TypeScript, and Tailwind CSS. You will collaborate with product designers to implement pixel-perfect user interfaces, integrate REST API endpoints, and optimize web app performance.",
    location: "Bengaluru, Karnataka",
    type: "hybrid",
    internship_type: "Full-time",
    duration: "6 Months",
    stipend: "₹28,000 / month",
    salary_range: "₹28,000 / month",
    openings_count: 3,
    deadline: "2026-08-30",
    start_date: "2026-09-01",
    end_date: "2027-02-28",
    employment_type: "Internship",
    required_experience: "Fresher / Undergrad",
    minimum_cgpa: "7.0 / 10",
    requirements: [
      "Strong proficiency in JavaScript ES6+ & TypeScript",
      "Experience building React.js component trees",
      "Understanding of REST APIs and async state management",
      "Familiarity with Git and modern CSS frameworks like Tailwind",
    ],
    skills_needed: ["React", "TypeScript", "HTML", "CSS", "Tailwind CSS", "Redux"],
    preferred_skills: ["Next.js", "Zustand", "Framer Motion"],
    responsibilities: [
      "Develop reusable React UI components",
      "Integrate backend RESTful APIs",
      "Optimize frontend bundle sizes and web vitals",
    ],
    eligibility: "B.Tech / BE / MCA Students (3rd & 4th Year)",
    perks: ["Certificate of Completion", "Flexible Working Hours", "Pre-Placement Offer (PPO) Opportunity"],
    selection_process: ["Online Skill Test", "Technical Coding Interview", "HR Culture Round"],
    status: "approved",
    created_at: "2026-07-30T00:00:00.000Z",
    tags: ["Frontend", "React", "TypeScript", "Web Development"],
    company: DEMO_COMPANIES[8],
  },
  {
    id: "i0000000-0000-0000-0000-000000000002",
    company_id: "c0000000-0000-0000-0000-000000000004",
    title: "Next.js Full Stack Developer Intern",
    department: "Engineering",
    description: "PixelStack Software is seeking a motivated Next.js Developer Intern to work on server-side rendered and App Router web platforms. You will develop React Server Components, construct API routes, integrate PostgreSQL databases, and build ultra-fast SaaS applications.",
    location: "Remote",
    type: "remote",
    internship_type: "Full-time",
    duration: "6 Months",
    stipend: "₹35,000 / month",
    salary_range: "₹35,000 / month",
    openings_count: 2,
    deadline: "2026-08-25",
    start_date: "2026-09-01",
    end_date: "2027-02-28",
    employment_type: "Internship",
    required_experience: "0-1 Year Experience / Projects",
    minimum_cgpa: "7.5 / 10",
    requirements: [
      "Hands-on experience with Next.js App Router and React",
      "Proficiency in TypeScript and Node.js",
      "Understanding of Server Actions and SQL database queries",
      "Familiarity with Vercel deployment pipelines",
    ],
    skills_needed: ["Next.js", "React", "TypeScript", "Node.js", "Tailwind CSS", "PostgreSQL"],
    preferred_skills: ["Prisma", "Supabase", "Docker"],
    responsibilities: [
      "Build dynamic Server Components and Client Components",
      "Optimize SSR and SSG rendering performance",
      "Design relational PostgreSQL database schemas",
    ],
    eligibility: "B.Tech / BE (CS/IT) 2025/2026 Batch",
    perks: ["Remote Work Allowance", "Learning Stipend", "Mentorship from Senior Architects"],
    selection_process: ["Project Portfolio Review", "System Design & Live Coding", "HR Round"],
    status: "approved",
    created_at: "2026-07-30T00:00:00.000Z",
    tags: ["Full Stack", "Next.js", "React", "TypeScript", "Node.js"],
    company: DEMO_COMPANIES[3],
  },
  {
    id: "i0000000-0000-0000-0000-000000000003",
    company_id: "c0000000-0000-0000-0000-000000000014",
    title: "React & UI Engineer Intern",
    department: "UI/UX & Frontend",
    description: "Work with InnoSpark Technologies design team to translate Figma design systems into scalable React component libraries. You will focus on micro-interactions, responsive layouts, accessibility compliance, and CSS animations.",
    location: "Chennai, Tamil Nadu",
    type: "hybrid",
    internship_type: "Full-time",
    duration: "3 Months",
    stipend: "₹25,000 / month",
    salary_range: "₹25,000 / month",
    openings_count: 4,
    deadline: "2026-08-20",
    start_date: "2026-08-25",
    end_date: "2026-11-25",
    employment_type: "Internship",
    required_experience: "Fresher",
    minimum_cgpa: "6.5 / 10",
    requirements: [
      "Proficiency in HTML5, CSS3, and JavaScript",
      "Experience with React hooks and component lifecycle",
      "Eye for UI design details and Figma translation",
      "Knowledge of responsive design principles",
    ],
    skills_needed: ["React", "JavaScript", "CSS", "HTML", "Figma", "Responsive Design"],
    preferred_skills: ["Tailwind CSS", "Storybook", "Framer Motion"],
    responsibilities: [
      "Convert Figma wireframes into interactive React components",
      "Ensure cross-browser compatibility and accessibility",
      "Maintain component documentation in Storybook",
    ],
    eligibility: "Open to all Engineering & Design Undergraduates",
    perks: ["UI Design Mentorship", "Certificate", "Team Lunches & Stipend"],
    selection_process: ["UI Design Assignment", "Technical Interview"],
    status: "approved",
    created_at: "2026-07-30T00:00:00.000Z",
    tags: ["React", "UI/UX", "Frontend", "Design"],
    company: DEMO_COMPANIES[13],
  },
  {
    id: "i0000000-0000-0000-0000-000000000004",
    company_id: "c0000000-0000-0000-0000-000000000001",
    title: "Angular Developer Intern",
    department: "Enterprise Web",
    description: "TechNova Solutions is looking for an Angular Developer Intern to build enterprise web portals. You will write clean TypeScript code, work with RxJS observables, integrate RESTful APIs, and participate in Agile code reviews.",
    location: "Bengaluru, Karnataka",
    type: "on-site",
    internship_type: "Full-time",
    duration: "6 Months",
    stipend: "₹30,000 / month",
    salary_range: "₹30,000 / month",
    openings_count: 2,
    deadline: "2026-09-05",
    start_date: "2026-09-10",
    end_date: "2027-03-10",
    employment_type: "Internship",
    required_experience: "Fresher / Projects",
    minimum_cgpa: "7.0 / 10",
    requirements: [
      "Solid understanding of TypeScript and Object-Oriented Programming",
      "Familiarity with Angular framework architecture (Modules, Components, Services)",
      "Understanding of RxJS and HTTP client integration",
    ],
    skills_needed: ["Angular", "TypeScript", "RxJS", "HTML5", "CSS3", "REST API"],
    preferred_skills: ["NgRx", "Bootstrap", "Jasmine/Karma Testing"],
    responsibilities: [
      "Develop modular Angular modules and reactive forms",
      "Manage asynchronous data streams using RxJS",
      "Write unit tests for core services",
    ],
    eligibility: "B.Tech CS/IT/ECE 4th Year",
    perks: ["PPO Opportunity", "Enterprise Certification", "Free Commute & Meals"],
    selection_process: ["Aptitude & Coding Test", "Technical Interview"],
    status: "approved",
    created_at: "2026-07-30T00:00:00.000Z",
    tags: ["Angular", "TypeScript", "Frontend", "Enterprise"],
    company: DEMO_COMPANIES[0],
  },
  {
    id: "i0000000-0000-0000-0000-000000000005",
    company_id: "c0000000-0000-0000-0000-000000000002",
    title: "Vue.js Frontend Engineer Intern",
    department: "Engineering",
    description: "ByteForge Technologies needs a creative Vue.js Frontend Developer Intern to craft reactive web applications using Vue 3, Composition API, and Nuxt.js.",
    location: "Remote",
    type: "remote",
    internship_type: "Full-time",
    duration: "4 Months",
    stipend: "₹26,000 / month",
    salary_range: "₹26,000 / month",
    openings_count: 2,
    deadline: "2026-08-18",
    start_date: "2026-08-22",
    end_date: "2026-12-22",
    employment_type: "Internship",
    required_experience: "Fresher",
    minimum_cgpa: "6.5 / 10",
    requirements: [
      "Proficiency in JavaScript and Vue.js 3 Composition API",
      "Experience with state management using Pinia or Vuex",
      "Understanding of web performance optimization",
    ],
    skills_needed: ["Vue.js", "Nuxt.js", "JavaScript", "Tailwind CSS", "HTML5"],
    preferred_skills: ["TypeScript", "Vite", "GraphQL"],
    responsibilities: [
      "Build single-page web applications with Vue 3",
      "Integrate REST and GraphQL APIs",
      "Optimize component rendering",
    ],
    eligibility: "Undergraduate Engineering Students",
    perks: ["Flexible Timings", "Certificate", "Project Sponsorship"],
    selection_process: ["Code Screening", "Technical Discussion"],
    status: "approved",
    created_at: "2026-07-30T00:00:00.000Z",
    tags: ["Vue.js", "Nuxt.js", "Frontend", "JavaScript"],
    company: DEMO_COMPANIES[1],
  },
  {
    id: "i0000000-0000-0000-0000-000000000006",
    company_id: "c0000000-0000-0000-0000-000000000002",
    title: "Backend Developer Intern (Node.js & Express)",
    department: "Backend Systems",
    description: "Build scalable server-side applications at ByteForge Technologies. Responsibilities include developing RESTful APIs with Node.js and Express, managing MongoDB collections, implementing JWT authentication, and writing unit tests.",
    location: "Hyderabad, Telangana",
    type: "hybrid",
    internship_type: "Full-time",
    duration: "6 Months",
    stipend: "₹32,000 / month",
    salary_range: "₹32,000 / month",
    openings_count: 3,
    deadline: "2026-08-28",
    start_date: "2026-09-01",
    end_date: "2027-02-28",
    employment_type: "Internship",
    required_experience: "Fresher / Projects",
    minimum_cgpa: "7.0 / 10",
    requirements: [
      "Strong command of JavaScript/Node.js asynchronous programming",
      "Experience building REST APIs with Express.js",
      "Knowledge of MongoDB/Mongoose or SQL databases",
      "Understanding of JWT security and middleware",
    ],
    skills_needed: ["Node.js", "Express", "MongoDB", "REST API", "JWT", "TypeScript"],
    preferred_skills: ["Redis", "Docker", "Jest Testing"],
    responsibilities: [
      "Design database models and API endpoints",
      "Implement secure user authentication & authorization",
      "Optimize API response times and caching",
    ],
    eligibility: "B.Tech / MCA Final Year Students",
    perks: ["PPO Potential", "Certification Allowance", "Hybrid Work Model"],
    selection_process: ["API Coding Challenge", "Technical Round", "HR Interview"],
    status: "approved",
    created_at: "2026-07-30T00:00:00.000Z",
    tags: ["Node.js", "Backend", "Express", "MongoDB"],
    company: DEMO_COMPANIES[1],
  },
  {
    id: "i0000000-0000-0000-0000-000000000007",
    company_id: "c0000000-0000-0000-0000-000000000005",
    title: "Java Spring Boot Developer Intern",
    department: "Enterprise Backend",
    description: "CodeSprint Technologies is hiring a Java Developer Intern for high-performance financial microservices. You will work with Core Java, Spring Boot, Hibernate ORM, and MySQL database optimization.",
    location: "Chennai, Tamil Nadu",
    type: "on-site",
    internship_type: "Full-time",
    duration: "6 Months",
    stipend: "₹38,000 / month",
    salary_range: "₹38,000 / month",
    openings_count: 5,
    deadline: "2026-09-10",
    start_date: "2026-09-15",
    end_date: "2027-03-15",
    employment_type: "Internship",
    required_experience: "Fresher",
    minimum_cgpa: "7.5 / 10",
    requirements: [
      "Strong OOP knowledge in Java 11/17",
      "Hands-on experience with Spring Boot framework",
      "Understanding of relational databases (MySQL/PostgreSQL)",
      "Basic knowledge of Maven and Git",
    ],
    skills_needed: ["Java", "Spring Boot", "Hibernate", "MySQL", "REST API", "Maven"],
    preferred_skills: ["Microservices", "Kafka", "Docker"],
    responsibilities: [
      "Develop Spring Boot REST microservices",
      "Write optimized SQL queries and Hibernate mappings",
      "Participate in daily Scrum standups",
    ],
    eligibility: "B.Tech CS/IT 2025/2026 Batch",
    perks: ["Competitive Stipend", "PPO for Top Performers", "Onsite Cafeteria"],
    selection_process: ["Online Aptitude & Java Assessment", "Technical Interview", "HR Round"],
    status: "approved",
    created_at: "2026-07-30T00:00:00.000Z",
    tags: ["Java", "Spring Boot", "Backend", "FinTech"],
    company: DEMO_COMPANIES[4],
  },
  {
    id: "i0000000-0000-0000-0000-000000000008",
    company_id: "c0000000-0000-0000-0000-000000000013",
    title: "Python Backend Developer Intern (Django)",
    department: "Backend & Cloud",
    description: "LogicLoop Software is recruiting a Python Backend Intern to design data processing APIs using Django and Flask. You will write clean Python code, design database schemas, and optimize query execution.",
    location: "Hyderabad, Telangana",
    type: "remote",
    internship_type: "Full-time",
    duration: "6 Months",
    stipend: "₹30,000 / month",
    salary_range: "₹30,000 / month",
    openings_count: 3,
    deadline: "2026-08-22",
    start_date: "2026-09-01",
    end_date: "2027-02-28",
    employment_type: "Internship",
    required_experience: "Fresher",
    minimum_cgpa: "6.5 / 10",
    requirements: [
      "Strong Python programming skills",
      "Experience with Django or Flask web frameworks",
      "Understanding of relational database modeling (PostgreSQL)",
      "Knowledge of RESTful API principles",
    ],
    skills_needed: ["Python", "Django", "Flask", "PostgreSQL", "REST API", "Redis"],
    preferred_skills: ["Celery", "FastAPI", "Docker"],
    responsibilities: [
      "Build scalable Django web endpoints",
      "Manage database migrations and query optimization",
      "Write automated pytest test cases",
    ],
    eligibility: "B.Tech / B.Sc Computer Science Students",
    perks: ["Remote Work Flexibility", "Certificate", "Mentorship"],
    selection_process: ["Python Code Screen", "Technical Interview"],
    status: "approved",
    created_at: "2026-07-30T00:00:00.000Z",
    tags: ["Python", "Django", "Backend", "API"],
    company: DEMO_COMPANIES[12],
  },
  {
    id: "i0000000-0000-0000-0000-000000000009",
    company_id: "c0000000-0000-0000-0000-000000000013",
    title: "FastAPI Microservices Developer Intern",
    department: "API Infrastructure",
    description: "Build high-speed asynchronous APIs with Python FastAPI at LogicLoop Software. You will work with Pydantic validation models, AsyncPG, Docker containers, and OpenAPI documentation.",
    location: "Pune, Maharashtra",
    type: "remote",
    internship_type: "Full-time",
    duration: "4 Months",
    stipend: "₹32,000 / month",
    salary_range: "₹32,000 / month",
    openings_count: 2,
    deadline: "2026-08-15",
    start_date: "2026-08-20",
    end_date: "2026-12-20",
    employment_type: "Internship",
    required_experience: "Fresher / Projects",
    minimum_cgpa: "7.0 / 10",
    requirements: [
      "Proficiency in Python 3.9+ async/await syntax",
      "Hands-on project experience with FastAPI",
      "Understanding of Docker containerization",
      "Familiarity with PostgreSQL database design",
    ],
    skills_needed: ["Python", "FastAPI", "PostgreSQL", "Docker", "REST API"],
    preferred_skills: ["Redis", "SQLAlchemy", "Alembic"],
    responsibilities: [
      "Develop async microservices using FastAPI",
      "Write OpenAPI endpoint specifications",
      "Containerize applications with Docker Compose",
    ],
    eligibility: "Engineering Undergraduate / Postgraduate",
    perks: ["Fully Remote", "PPO Potential", "Hardware Allowance"],
    selection_process: ["FastAPI Coding Task", "Technical Interview"],
    status: "approved",
    created_at: "2026-07-30T00:00:00.000Z",
    tags: ["FastAPI", "Python", "Microservices", "Docker"],
    company: DEMO_COMPANIES[12],
  },
  {
    id: "i0000000-0000-0000-0000-000000000010",
    company_id: "c0000000-0000-0000-0000-000000000011",
    title: "Full Stack Developer Intern (MERN Stack)",
    department: "Product Engineering",
    description: "Innovexa Solutions is looking for a versatile MERN Stack Intern to build end-to-end web features. You will work across React frontends, Node.js/Express APIs, MongoDB schemas, and Tailwind CSS styling.",
    location: "Bengaluru, Karnataka",
    type: "hybrid",
    internship_type: "Full-time",
    duration: "6 Months",
    stipend: "₹40,000 / month",
    salary_range: "₹40,000 / month",
    openings_count: 4,
    deadline: "2026-08-30",
    start_date: "2026-09-01",
    end_date: "2027-02-28",
    employment_type: "Internship",
    required_experience: "0-1 Year / Full Stack Projects",
    minimum_cgpa: "7.0 / 10",
    requirements: [
      "Proficiency across React, Node.js, Express, and MongoDB",
      "Experience with TypeScript and modern JavaScript",
      "Understanding of Git workflow and pull requests",
      "Ability to build responsive web apps from scratch",
    ],
    skills_needed: ["React", "Node.js", "Express", "MongoDB", "TypeScript", "Tailwind CSS"],
    preferred_skills: ["Next.js", "Redux Toolkit", "AWS S3"],
    responsibilities: [
      "Build responsive UI views and backend REST controllers",
      "Implement user authentication and MongoDB data indexing",
      "Collaborate with product managers and QA team",
    ],
    eligibility: "B.Tech CS/IT/ECE 3rd & 4th Year",
    perks: ["Top Stipend Tier", "PPO Track", "Learning Credits"],
    selection_process: ["Full Stack Assessment", "Technical & System Design Interview", "HR Round"],
    status: "approved",
    created_at: "2026-07-30T00:00:00.000Z",
    tags: ["MERN", "Full Stack", "React", "Node.js", "MongoDB"],
    company: DEMO_COMPANIES[10],
  },
  {
    id: "i0000000-0000-0000-0000-000000000011",
    company_id: "c0000000-0000-0000-0000-000000000012",
    title: "Full Stack Java Engineer Intern",
    department: "Enterprise Web Systems",
    description: "CoreMatrix Labs is seeking a Full Stack Java Intern to build enterprise web dashboards. You will combine Java Spring Boot backends with React frontend interfaces and PostgreSQL databases.",
    location: "Pune, Maharashtra",
    type: "on-site",
    internship_type: "Full-time",
    duration: "6 Months",
    stipend: "₹42,000 / month",
    salary_range: "₹42,000 / month",
    openings_count: 3,
    deadline: "2026-08-30",
    start_date: "2026-09-05",
    end_date: "2027-03-05",
    employment_type: "Internship",
    required_experience: "Fresher / Projects",
    minimum_cgpa: "7.5 / 10",
    requirements: [
      "Strong Java Spring Boot knowledge",
      "Familiarity with React.js or Angular",
      "Proficiency in SQL database design",
      "Basic understanding of Docker containers",
    ],
    skills_needed: ["Java", "Spring Boot", "React", "PostgreSQL", "TypeScript", "Docker"],
    preferred_skills: ["Microservices", "REST API", "Kubernetes"],
    responsibilities: [
      "Develop Spring Boot REST APIs and React frontend modules",
      "Optimize relational database schema and queries",
      "Write end-to-end integration tests",
    ],
    eligibility: "B.Tech CS/IT 2025/2026 Batch",
    perks: ["PPO Opportunity", "Premium Allowance", "Mentorship"],
    selection_process: ["Java Coding Test", "Technical Interview", "HR Round"],
    status: "approved",
    created_at: "2026-07-30T00:00:00.000Z",
    tags: ["Java", "Spring Boot", "React", "Full Stack"],
    company: DEMO_COMPANIES[11],
  },
  {
    id: "i0000000-0000-0000-0000-000000000012",
    company_id: "c0000000-0000-0000-0000-000000000006",
    title: "AI & Computer Vision Engineer Intern",
    department: "AI Research Lab",
    description: "Join VisionAI Labs to develop deep learning models for image recognition, object detection, and video stream processing. You will work with PyTorch, OpenCV, YOLO, and TensorRT optimization pipelines.",
    location: "Bengaluru, Karnataka",
    type: "hybrid",
    internship_type: "Full-time",
    duration: "6 Months",
    stipend: "₹50,000 / month",
    salary_range: "₹50,000 / month",
    openings_count: 2,
    deadline: "2026-08-20",
    start_date: "2026-09-01",
    end_date: "2027-02-28",
    employment_type: "Internship",
    required_experience: "AI / ML Projects Experience",
    minimum_cgpa: "8.0 / 10",
    requirements: [
      "Strong Python math/algorithm background",
      "Experience with PyTorch or TensorFlow",
      "Hands-on computer vision project experience with OpenCV",
      "Familiarity with Convolutional Neural Networks (CNNs)",
    ],
    skills_needed: ["Python", "TensorFlow", "PyTorch", "Machine Learning", "Computer Vision", "OpenCV"],
    preferred_skills: ["YOLO", "TensorRT", "CUDA"],
    responsibilities: [
      "Train computer vision models on custom datasets",
      "Benchmark model inference performance",
      "Deploy models on edge and cloud servers",
    ],
    eligibility: "B.Tech/M.Tech/MS in CS, AI, or Data Science",
    perks: ["Research Publication Support", "High Stipend", "GPU Cloud Credits"],
    selection_process: ["Machine Learning Challenge", "Technical Interview by Lead AI Scientist"],
    status: "approved",
    created_at: "2026-07-30T00:00:00.000Z",
    tags: ["AI", "Computer Vision", "PyTorch", "TensorFlow", "Python"],
    company: DEMO_COMPANIES[5],
  },
  {
    id: "i0000000-0000-0000-0000-000000000013",
    company_id: "c0000000-0000-0000-0000-000000000020",
    title: "Generative AI & LLM Research Intern",
    department: "GenAI & LLM Lab",
    description: "BrightMind AI is offering a cutting-edge research internship to build RAG (Retrieval-Augmented Generation) systems, fine-tune open-weight LLMs (Llama/Mistral), and build AI agent workflows using LangChain.",
    location: "Bengaluru, Karnataka",
    type: "remote",
    internship_type: "Full-time",
    duration: "6 Months",
    stipend: "₹55,000 / month",
    salary_range: "₹55,000 / month",
    openings_count: 2,
    deadline: "2026-08-25",
    start_date: "2026-09-01",
    end_date: "2027-02-28",
    employment_type: "Internship",
    required_experience: "Python & LLM Project Portfolio",
    minimum_cgpa: "8.0 / 10",
    requirements: [
      "Deep understanding of Large Language Models and NLP",
      "Proficiency in Python and PyTorch",
      "Experience with LangChain, LlamaIndex, or OpenAI APIs",
      "Understanding of vector databases (FAISS, Chroma, Pinecone)",
    ],
    skills_needed: ["Python", "PyTorch", "LLMs", "NLP", "LangChain", "OpenAI API", "Transformers"],
    preferred_skills: ["QLoRA Fine-tuning", "vLLM", "Vector Search"],
    responsibilities: [
      "Build RAG pipelines with vector database indexing",
      "Fine-tune open-source LLMs on specialized domain datasets",
      "Evaluate LLM output accuracy and hallucination metrics",
    ],
    eligibility: "B.Tech/M.Tech CS/AI Final Year Students",
    perks: ["Top Industry Stipend", "Generative AI Certification", "Remote Flexibility"],
    selection_process: ["LLM Architecture & Coding Assessment", "AI Scientist Interview"],
    status: "approved",
    created_at: "2026-07-30T00:00:00.000Z",
    tags: ["Generative AI", "LLMs", "LangChain", "Python", "PyTorch"],
    company: DEMO_COMPANIES[19],
  },
  {
    id: "i0000000-0000-0000-0000-000000000014",
    company_id: "c0000000-0000-0000-0000-000000000018",
    title: "Data Science & Machine Learning Intern",
    department: "Analytics & ML",
    description: "DataVerse Analytics is looking for a Data Science Intern to clean complex datasets, perform exploratory data analysis, build predictive Machine Learning models (Random Forest, XGBoost), and present statistical insights.",
    location: "Hyderabad, Telangana",
    type: "hybrid",
    internship_type: "Full-time",
    duration: "6 Months",
    stipend: "₹45,000 / month",
    salary_range: "₹45,000 / month",
    openings_count: 3,
    deadline: "2026-08-30",
    start_date: "2026-09-05",
    end_date: "2027-03-05",
    employment_type: "Internship",
    required_experience: "Fresher / Projects",
    minimum_cgpa: "7.5 / 10",
    requirements: [
      "Proficiency in Python data stack (Pandas, NumPy, Scikit-learn)",
      "Strong SQL querying and data manipulation skills",
      "Understanding of statistical analysis and hypothesis testing",
    ],
    skills_needed: ["Python", "Pandas", "NumPy", "Scikit-learn", "SQL", "Data Visualization"],
    preferred_skills: ["XGBoost", "Matplotlib", "Jupyter Notebooks"],
    responsibilities: [
      "Clean raw data pipelines and engineer predictive features",
      "Train ML classification and regression algorithms",
      "Create data storytelling dashboards",
    ],
    eligibility: "B.Tech / M.Sc / MCA Students",
    perks: ["PPO Potential", "Data Science Mentorship", "Competitive Stipend"],
    selection_process: ["Data Analysis Coding Test", "Technical Interview"],
    status: "approved",
    created_at: "2026-07-30T00:00:00.000Z",
    tags: ["Data Science", "Machine Learning", "Python", "SQL", "Pandas"],
    company: DEMO_COMPANIES[17],
  },
  {
    id: "i0000000-0000-0000-0000-000000000015",
    company_id: "c0000000-0000-0000-0000-000000000007",
    title: "Data Analyst Intern",
    department: "Business Intelligence",
    description: "QuantumSoft Solutions seeks a detail-oriented Data Analyst Intern to create Power BI dashboards, write SQL queries, extract business insights, and automate weekly reporting metrics.",
    location: "Gurugram, Haryana",
    type: "hybrid",
    internship_type: "Full-time",
    duration: "4 Months",
    stipend: "₹28,000 / month",
    salary_range: "₹28,000 / month",
    openings_count: 4,
    deadline: "2026-08-20",
    start_date: "2026-08-25",
    end_date: "2026-12-25",
    employment_type: "Internship",
    required_experience: "Fresher",
    minimum_cgpa: "6.5 / 10",
    requirements: [
      "Advanced SQL skills (joins, aggregations, window functions)",
      "Experience with Power BI or Tableau visualization tools",
      "Proficiency in Excel and basic Python scripting",
    ],
    skills_needed: ["SQL", "Python", "Power BI", "Excel", "Pandas", "Data Analysis"],
    preferred_skills: ["Tableau", "DAX", "BigQuery"],
    responsibilities: [
      "Build Power BI dashboards for operational KPIs",
      "Write complex SQL queries for data extraction",
      "Automate reporting workflows with Python",
    ],
    eligibility: "Graduates / Postgraduates in Science/Engineering/Commerce",
    perks: ["Power BI Certification Support", "Stipend", "Flexible Hours"],
    selection_process: ["SQL Test", "Data Visualization Case Study"],
    status: "approved",
    created_at: "2026-07-30T00:00:00.000Z",
    tags: ["Data Analyst", "SQL", "Power BI", "Python"],
    company: DEMO_COMPANIES[6],
  },
  {
    id: "i0000000-0000-0000-0000-000000000016",
    company_id: "c0000000-0000-0000-0000-000000000003",
    title: "DevOps & Cloud Engineer Intern",
    department: "Infrastructure & DevOps",
    description: "CloudNest Labs is recruiting a DevOps Intern to automate CI/CD build pipelines, containerize microservices with Docker, manage Kubernetes clusters, and provision AWS infrastructure using Terraform.",
    location: "Pune, Maharashtra",
    type: "remote",
    internship_type: "Full-time",
    duration: "6 Months",
    stipend: "₹36,000 / month",
    salary_range: "₹36,000 / month",
    openings_count: 2,
    deadline: "2026-08-25",
    start_date: "2026-09-01",
    end_date: "2027-02-28",
    employment_type: "Internship",
    required_experience: "Linux & Docker Knowledge",
    minimum_cgpa: "7.0 / 10",
    requirements: [
      "Hands-on Linux command line proficiency",
      "Understanding of Docker containerization and Dockerfiles",
      "Basic knowledge of Kubernetes and AWS cloud concepts",
      "Familiarity with GitHub Actions or Jenkins CI/CD",
    ],
    skills_needed: ["Docker", "Kubernetes", "AWS", "CI/CD", "Linux", "Terraform"],
    preferred_skills: ["Helm", "Prometheus", "Grafana"],
    responsibilities: [
      "Write Dockerfiles and Kubernetes deployment manifests",
      "Configure CI/CD build automation in GitHub Actions",
      "Monitor cloud resource utilization",
    ],
    eligibility: "B.Tech CS/IT/ECE Final Year",
    perks: ["AWS Certification Voucher", "Remote Flexibility", "PPO Track"],
    selection_process: ["Linux & DevOps Screening", "Technical Interview"],
    status: "approved",
    created_at: "2026-07-30T00:00:00.000Z",
    tags: ["DevOps", "Docker", "Kubernetes", "AWS", "Linux"],
    company: DEMO_COMPANIES[2],
  },
  {
    id: "i0000000-0000-0000-0000-000000000017",
    company_id: "c0000000-0000-0000-0000-000000000019",
    title: "AWS Cloud Infrastructure Intern",
    department: "Cloud Engineering",
    description: "CloudFusion Technologies is seeking an AWS Cloud Intern to configure EC2 instances, S3 storage buckets, VPC networking, IAM security policies, and Serverless Lambda functions.",
    location: "Noida, Uttar Pradesh",
    type: "remote",
    internship_type: "Full-time",
    duration: "5 Months",
    stipend: "₹34,000 / month",
    salary_range: "₹34,000 / month",
    openings_count: 3,
    deadline: "2026-08-30",
    start_date: "2026-09-01",
    end_date: "2027-01-31",
    employment_type: "Internship",
    required_experience: "Fresher",
    minimum_cgpa: "6.8 / 10",
    requirements: [
      "Understanding of core AWS services (EC2, S3, RDS, Lambda)",
      "Basic Linux administration and bash scripting",
      "Understanding of networking principles (DNS, HTTP, Subnets)",
    ],
    skills_needed: ["AWS", "Linux", "Docker", "Python", "Networking", "Terraform"],
    preferred_skills: ["AWS CloudFormation", "Serverless"],
    responsibilities: [
      "Deploy and manage AWS EC2 & S3 infrastructure",
      "Configure VPC security groups and IAM access policies",
      "Automate maintenance scripts in Python/Bash",
    ],
    eligibility: "Engineering Undergraduates",
    perks: ["Cloud Credits", "Certification Support", "Certificate"],
    selection_process: ["AWS Fundamentals Quiz", "Technical Interview"],
    status: "approved",
    created_at: "2026-07-30T00:00:00.000Z",
    tags: ["AWS", "Cloud", "Linux", "DevOps"],
    company: DEMO_COMPANIES[18],
  },
  {
    id: "i0000000-0000-0000-0000-000000000018",
    company_id: "c0000000-0000-0000-0000-000000000017",
    title: "Cybersecurity & Application Security Intern",
    department: "Information Security",
    description: "CyberShield Security is looking for an AppSec Intern to conduct OWASP vulnerability assessments, perform penetration testing with Burp Suite, analyze packet captures in Wireshark, and audit source code.",
    location: "Mumbai, Maharashtra",
    type: "on-site",
    internship_type: "Full-time",
    duration: "6 Months",
    stipend: "₹35,000 / month",
    salary_range: "₹35,000 / month",
    openings_count: 2,
    deadline: "2026-08-20",
    start_date: "2026-09-01",
    end_date: "2027-02-28",
    employment_type: "Internship",
    required_experience: "Cybersecurity Projects / CEH",
    minimum_cgpa: "7.0 / 10",
    requirements: [
      "Understanding of OWASP Top 10 vulnerabilities",
      "Experience using Burp Suite, Nmap, and Wireshark",
      "Solid understanding of TCP/IP networking and Linux OS",
    ],
    skills_needed: ["Networking", "OWASP", "Burp Suite", "Wireshark", "Linux", "Ethical Hacking"],
    preferred_skills: ["Metasploit", "Python Scripting", "CEH"],
    responsibilities: [
      "Perform web application vulnerability scans",
      "Document security audit findings and mitigation steps",
      "Participate in red-team security simulations",
    ],
    eligibility: "B.Tech CS/IT or Cybersecurity Certifications (CEH/EJPT)",
    perks: ["Security Lab Access", "PPO Potential", "Certification Sponsorship"],
    selection_process: ["CTF / Security Challenge", "Technical Interview"],
    status: "approved",
    created_at: "2026-07-30T00:00:00.000Z",
    tags: ["Cybersecurity", "Ethical Hacking", "OWASP", "Burp Suite"],
    company: DEMO_COMPANIES[16],
  },
  {
    id: "i0000000-0000-0000-0000-000000000019",
    company_id: "c0000000-0000-0000-0000-000000000010",
    title: "Network Security & SOC Analyst Intern",
    department: "Security Operations",
    description: "BluePeak Systems is hiring a SOC Intern to monitor security logs, inspect SIEM events, audit firewall rules, and assist in incident response procedures.",
    location: "Mumbai, Maharashtra",
    type: "hybrid",
    internship_type: "Full-time",
    duration: "6 Months",
    stipend: "₹32,000 / month",
    salary_range: "₹32,000 / month",
    openings_count: 2,
    deadline: "2026-08-25",
    start_date: "2026-09-01",
    end_date: "2027-02-28",
    employment_type: "Internship",
    required_experience: "Fresher",
    minimum_cgpa: "6.8 / 10",
    requirements: [
      "Strong networking basics (OSI model, Subnetting, Firewalls)",
      "Hands-on Linux command line skills",
      "Scripting knowledge in Python or Bash",
    ],
    skills_needed: ["Linux", "Networking", "Python", "OWASP", "Penetration Testing"],
    preferred_skills: ["Splunk", "Snort", "CompTIA Security+"],
    responsibilities: [
      "Monitor live network traffic logs in SIEM tool",
      "Analyze malicious packet alerts",
      "Draft incident report tickets",
    ],
    eligibility: "B.Tech CS/IT Students",
    perks: ["SOC Training", "PPO Track", "Allowance"],
    selection_process: ["Networking Assessment", "Technical Interview"],
    status: "approved",
    created_at: "2026-07-30T00:00:00.000Z",
    tags: ["Cybersecurity", "Networking", "SOC", "Linux"],
    company: DEMO_COMPANIES[9],
  },
  {
    id: "i0000000-0000-0000-0000-000000000020",
    company_id: "c0000000-0000-0000-0000-000000000008",
    title: "Native Android Developer Intern (Kotlin)",
    department: "Mobile Development",
    description: "SkyNet Digital is seeking an Android Developer Intern to build native mobile apps using Kotlin, Jetpack Compose, Retrofit, and Coroutines.",
    location: "Noida, Uttar Pradesh",
    type: "hybrid",
    internship_type: "Full-time",
    duration: "6 Months",
    stipend: "₹30,000 / month",
    salary_range: "₹30,000 / month",
    openings_count: 3,
    deadline: "2026-08-30",
    start_date: "2026-09-05",
    end_date: "2027-03-05",
    employment_type: "Internship",
    required_experience: "Android Projects Portfolio",
    minimum_cgpa: "7.0 / 10",
    requirements: [
      "Proficiency in Kotlin and Android SDK",
      "Experience with Jetpack Compose UI or XML layouts",
      "Understanding of REST API integration via Retrofit",
    ],
    skills_needed: ["Kotlin", "Java", "Android SDK", "Jetpack Compose", "REST API", "Git"],
    preferred_skills: ["Room DB", "Dagger Hilt", "Coroutines"],
    responsibilities: [
      "Develop responsive Android app screens with Jetpack Compose",
      "Integrate RESTful JSON endpoints",
      "Write clean Kotlin architecture code",
    ],
    eligibility: "B.Tech CS/IT/ECE 3rd & 4th Year",
    perks: ["Device Allowance", "PPO Track", "Certificate"],
    selection_process: ["Android Coding Challenge", "Technical Interview"],
    status: "approved",
    created_at: "2026-07-30T00:00:00.000Z",
    tags: ["Android", "Kotlin", "Mobile", "Jetpack Compose"],
    company: DEMO_COMPANIES[7],
  },
  {
    id: "i0000000-0000-0000-0000-000000000021",
    company_id: "c0000000-0000-0000-0000-000000000008",
    title: "Flutter Cross-Platform Developer Intern",
    department: "Mobile Development",
    description: "Build iOS and Android apps with Flutter and Dart at SkyNet Digital. Responsibilities include state management (Provider/Bloc), Firebase integration, and UI widget development.",
    location: "Remote",
    type: "remote",
    internship_type: "Full-time",
    duration: "4 Months",
    stipend: "₹28,000 / month",
    salary_range: "₹28,000 / month",
    openings_count: 2,
    deadline: "2026-08-20",
    start_date: "2026-08-25",
    end_date: "2026-12-25",
    employment_type: "Internship",
    required_experience: "Fresher / Flutter Apps",
    minimum_cgpa: "6.5 / 10",
    requirements: [
      "Proficiency in Dart programming language",
      "Experience building Flutter apps",
      "Understanding of state management (Provider/Bloc)",
      "Familiarity with Firebase integration",
    ],
    skills_needed: ["Flutter", "Dart", "Firebase", "REST API", "Git", "Mobile App Development"],
    preferred_skills: ["Riverpod", "Hive DB"],
    responsibilities: [
      "Construct multi-platform Flutter widgets",
      "Connect Firebase Auth & Firestore backends",
      "Publish builds to testing channels",
    ],
    eligibility: "Open to all Engineering Undergraduates",
    perks: ["Remote Work", "App Deployment Mentorship", "Certificate"],
    selection_process: ["Flutter Code Review", "Technical Discussion"],
    status: "approved",
    created_at: "2026-07-30T00:00:00.000Z",
    tags: ["Flutter", "Dart", "Mobile", "Firebase"],
    company: DEMO_COMPANIES[7],
  },
  {
    id: "i0000000-0000-0000-0000-000000000022",
    company_id: "c0000000-0000-0000-0000-000000000014",
    title: "UI/UX Product Design Intern",
    department: "Product Design",
    description: "InnoSpark Technologies is hiring a creative UI/UX Intern to design wireframes, user journeys, interactive Figma prototypes, and design systems for web and mobile apps.",
    location: "Chennai, Tamil Nadu",
    type: "remote",
    internship_type: "Full-time",
    duration: "3 Months",
    stipend: "₹25,000 / month",
    salary_range: "₹25,000 / month",
    openings_count: 2,
    deadline: "2026-08-15",
    start_date: "2026-08-20",
    end_date: "2026-11-20",
    employment_type: "Internship",
    required_experience: "Figma Portfolio Required",
    minimum_cgpa: "6.0 / 10",
    requirements: [
      "Mastery of Figma design tools",
      "Strong portfolio showcasing wireframing & prototyping",
      "Understanding of user research and usability testing",
    ],
    skills_needed: ["Figma", "UI/UX", "User Research", "Wireframing", "Prototyping", "Design Systems"],
    preferred_skills: ["Adobe XD", "Principle", "Lottie Animations"],
    responsibilities: [
      "Design user flows and high-fidelity wireframes in Figma",
      "Conduct usability tests with user personas",
      "Maintain design system token libraries",
    ],
    eligibility: "Students & Fresh Graduates with Design Portfolio",
    perks: ["Design Mentorship", "Portfolio Review", "Certificate"],
    selection_process: ["Figma Portfolio Review", "Design Challenge & Interview"],
    status: "approved",
    created_at: "2026-07-30T00:00:00.000Z",
    tags: ["UI/UX", "Figma", "Product Design", "Wireframing"],
    company: DEMO_COMPANIES[13],
  },
  {
    id: "i0000000-0000-0000-0000-000000000023",
    company_id: "c0000000-0000-0000-0000-000000000016",
    title: "QA Automation Engineer Intern",
    department: "Quality Assurance",
    description: "AlphaCode Systems is recruiting a QA Automation Intern to write automated web test scripts using Selenium WebDriver, execute Postman API collection tests, and report bug logs.",
    location: "Gurugram, Haryana",
    type: "on-site",
    internship_type: "Full-time",
    duration: "6 Months",
    stipend: "₹27,000 / month",
    salary_range: "₹27,000 / month",
    openings_count: 3,
    deadline: "2026-08-28",
    start_date: "2026-09-01",
    end_date: "2027-02-28",
    employment_type: "Internship",
    required_experience: "Fresher",
    minimum_cgpa: "6.5 / 10",
    requirements: [
      "Programming knowledge in Java or Python",
      "Experience with Selenium WebDriver framework",
      "Understanding of API testing using Postman",
    ],
    skills_needed: ["Selenium", "Java", "Python", "TestNG", "Postman", "API Testing"],
    preferred_skills: ["Cypress", "Jira", "Cucumber BDD"],
    responsibilities: [
      "Automate regression test suites with Selenium",
      "Validate API payloads with Postman assertions",
      "File detailed bug reports in Jira",
    ],
    eligibility: "B.Tech / BCA / MCA Graduates",
    perks: ["Testing Certification Support", "PPO Track", "Meals Provided"],
    selection_process: ["Automation Script Test", "Technical Interview"],
    status: "approved",
    created_at: "2026-07-30T00:00:00.000Z",
    tags: ["QA Automation", "Selenium", "Testing", "Java"],
    company: DEMO_COMPANIES[15],
  },
  {
    id: "i0000000-0000-0000-0000-000000000024",
    company_id: "c0000000-0000-0000-0000-000000000015",
    title: "Blockchain & Smart Contract Developer Intern",
    department: "Web3 & Blockchain",
    description: "FusionStack Pvt Ltd is seeking a Blockchain Developer Intern to write Solidity smart contracts, deploy EVM dApps, and integrate Web3.js/Ethers.js frontend libraries.",
    location: "Bengaluru, Karnataka",
    type: "remote",
    internship_type: "Full-time",
    duration: "6 Months",
    stipend: "₹48,000 / month",
    salary_range: "₹48,000 / month",
    openings_count: 2,
    deadline: "2026-08-22",
    start_date: "2026-09-01",
    end_date: "2027-02-28",
    employment_type: "Internship",
    required_experience: "Solidity Projects",
    minimum_cgpa: "7.5 / 10",
    requirements: [
      "Hands-on experience with Solidity and EVM architecture",
      "Familiarity with Hardhat or Foundry testing frameworks",
      "Understanding of Web3.js or Ethers.js integration",
    ],
    skills_needed: ["Solidity", "Ethereum", "Web3.js", "Smart Contracts", "TypeScript"],
    preferred_skills: ["Foundry", "OpenZeppelin", "IPFS"],
    responsibilities: [
      "Develop secure ERC-20 / ERC-721 smart contracts",
      "Perform unit tests and gas optimization",
      "Connect smart contracts to React dApp interfaces",
    ],
    eligibility: "B.Tech CS/IT Final Year Students",
    perks: ["High Tier Stipend", "Web3 Conference Sponsorship", "Remote Work"],
    selection_process: ["Solidity Coding Task", "Web3 Technical Interview"],
    status: "approved",
    created_at: "2026-07-30T00:00:00.000Z",
    tags: ["Blockchain", "Solidity", "Web3", "Ethereum"],
    company: DEMO_COMPANIES[14],
  },
  {
    id: "i0000000-0000-0000-0000-000000000025",
    company_id: "c0000000-0000-0000-0000-000000000001",
    title: "IoT & Embedded Systems Engineer Intern",
    department: "Hardware & IoT",
    description: "TechNova Solutions is hiring an IoT Intern to build micro-controller firmware using C/C++, program ESP32 and Raspberry Pi boards, and publish sensor data via MQTT protocols.",
    location: "Bengaluru, Karnataka",
    type: "on-site",
    internship_type: "Full-time",
    duration: "6 Months",
    stipend: "₹26,000 / month",
    salary_range: "₹26,000 / month",
    openings_count: 2,
    deadline: "2026-08-30",
    start_date: "2026-09-05",
    end_date: "2027-03-05",
    employment_type: "Internship",
    required_experience: "C/C++ & Embedded Hardware Knowledge",
    minimum_cgpa: "6.8 / 10",
    requirements: [
      "Strong command of C/C++ embedded programming",
      "Experience working with Arduino, ESP32, or Raspberry Pi",
      "Understanding of MQTT, I2C, and SPI communication protocols",
    ],
    skills_needed: ["C", "C++", "Embedded Systems", "IoT", "Raspberry Pi", "Arduino", "MQTT"],
    preferred_skills: ["FreeRTOS", "PCB Design", "Python"],
    responsibilities: [
      "Write microcontroller firmware in C/C++",
      "Interface environmental sensors with ESP32",
      "Transmit telemetry data over MQTT broker",
    ],
    eligibility: "B.Tech ECE/EEE/CS Students",
    perks: ["Hardware Development Kit", "Certificate", "PPO Track"],
    selection_process: ["Embedded C Assessment", "Hardware Lab Interview"],
    status: "approved",
    created_at: "2026-07-30T00:00:00.000Z",
    tags: ["IoT", "Embedded Systems", "C", "C++", "Raspberry Pi"],
    company: DEMO_COMPANIES[0],
  },
];
